### ISSUE TITLE
I am loving it, but keeps throwing errors?

### ISSUE THREAD

**Issue by Josep-Jesus-Bigorra-Algaba** [arwesjs/arwes#12]
### Subject of the issue

I have many React JSS errors that go like this:
index.js:1446 Warning: [JSS] Could not find the referenced rule hover in ArwesSounds(Frame), Themed, Dynamic.
function.console.(anonymous function) @ index.js:1446
warning @ browser.js:43
(anonymous) @ index.js:49
onProcessStyle @ index.js:108
onProcessStyle @ PluginsRegistry.js:97
onProcessRule @ PluginsRegistry.js:84
process @ RuleList.js:184
StyleSheet @ StyleSheet.js:93
createStyleSheet @ Jss.js:162
createState @ createHoc.js:315
Jss(ArwesSounds(Frame)) @ createHoc.js:223
constructClassInstance @ react-dom.development.js:13107
updateClassComponent @ react-dom.development.js:15086
beginWork @ react-dom.development.js:15980
performUnitOfWork @ react-dom.development.js:19102
workLoop @ react-dom.development.js:19143
renderRoot @ react-dom.development.js:19228
performWorkOnRoot @ react-dom.development.js:20165
performWork @ react-dom.development.js:20075
performSyncWork @ react-dom.development.js:20049
requestWork @ react-dom.development.js:19904
scheduleWork @ react-dom.development.js:19711
scheduleRootUpdate @ react-dom.development.js:20415
updateContainerAtExpirationTime @ react-dom.development.js:20441
updateContainer @ react-dom.development.js:20509
push../node_modules/react-dom/cjs/react-dom.development.js.ReactRoot.render @ react-dom.development.js:20820
(anonymous) @ react-dom.development.js:20974
unbatchedUpdates @ react-dom.development.js:20292
legacyRenderSubtreeIntoContainer @ react-dom.development.js:20970
render @ react-dom.development.js:21037
./src/index.js @ index.js:6
__webpack_require__ @ bootstrap:782
fn @ bootstrap:150
0 @ serviceWorker.js:135
__webpack_require__ @ bootstrap:782
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ main.chunk.js:1

index.js:1446 Warning: [JSS] Could not find the referenced rule circle2 in Loading, Themed, Dynamic.
function.console.(anonymous function) @ index.js:1446
warning @ browser.js:43
(anonymous) @ index.js:49
onProcessStyle @ index.js:108
onProcessStyle @ PluginsRegistry.js:97
onProcessRule @ PluginsRegistry.js:84
process @ RuleList.js:184
StyleSheet @ StyleSheet.js:93
createStyleSheet @ Jss.js:162
createState @ createHoc.js:315
Jss(ArwesSounds(Frame)) @ createHoc.js:223
constructClassInstance @ react-dom.development.js:13107
updateClassComponent @ react-dom.development.js:15086
beginWork @ react-dom.development.js:15980
performUnitOfWork @ react-dom.development.js:19102
workLoop @ react-dom.development.js:19143
renderRoot @ react-dom.development.js:19228
performWorkOnRoot @ react-dom.development.js:20165
performWork @ react-dom.development.js:20075
performSyncWork @ react-dom.development.js:20049
requestWork @ react-dom.development.js:19904
scheduleWork @ react-dom.development.js:19711
scheduleRootUpdate @ react-dom.development.js:20415
updateContainerAtExpirationTime @ react-dom.development.js:20441
updateContainer @ react-dom.development.js:20509
push../node_modules/react-dom/cjs/react-dom.development.js.ReactRoot.render @ react-dom.development.js:20820
(anonymous) @ react-dom.development.js:20974
unbatchedUpdates @ react-dom.development.js:20292
legacyRenderSubtreeIntoContainer @ react-dom.development.js:20970
render @ react-dom.development.js:21037
./src/index.js @ index.js:6
__webpack_require__ @ bootstrap:782
fn @ bootstrap:150
0 @ serviceWorker.js:135
__webpack_require__ @ bootstrap:782
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ main.chunk.js:1

index.js:1446 Warning: [JSS] Could not find the referenced rule hover in ArwesSounds(Frame), Themed, Dynamic.
function.console.(anonymous function) @ index.js:1446
warning @ browser.js:43
(anonymous) @ index.js:49
onProcessStyle @ index.js:108
onProcessStyle @ PluginsRegistry.js:97
onProcessRule @ PluginsRegistry.js:84
process @ RuleList.js:184
StyleSheet @ StyleSheet.js:93
createStyleSheet @ Jss.js:162
createState @ createHoc.js:315
Jss(ArwesSounds(Frame)) @ createHoc.js:223
constructClassInstance @ react-dom.development.js:13107
updateClassComponent @ react-dom.development.js:15086
beginWork @ react-dom.development.js:15980
performUnitOfWork @ react-dom.development.js:19102
workLoop @ react-dom.development.js:19143
renderRoot @ react-dom.development.js:19228
performWorkOnRoot @ react-dom.development.js:20165
performWork @ react-dom.development.js:20075
performSyncWork @ react-dom.development.js:20049
requestWork @ react-dom.development.js:19904
scheduleWork @ react-dom.development.js:19711
scheduleRootUpdate @ react-dom.development.js:20415
updateContainerAtExpirationTime @ react-dom.development.js:20441
updateContainer @ react-dom.development.js:20509
push../node_modules/react-dom/cjs/react-dom.development.js.ReactRoot.render @ react-dom.development.js:20820
(anonymous) @ react-dom.development.js:20974
unbatchedUpdates @ react-dom.development.js:20292
legacyRenderSubtreeIntoContainer @ react-dom.development.js:20970
render @ react-dom.development.js:21037
./src/index.js @ index.js:6
__webpack_require__ @ bootstrap:782
fn @ bootstrap:150
0 @ serviceWorker.js:135
__webpack_require__ @ bootstrap:782
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ main.chunk.js:1
index.js:1446 Warning: [JSS] Could not find the referenced rule hover in ArwesSounds(Frame), Themed, Dynamic.
function.console.(anonymous function) @ index.js:1446
warning @ browser.js:43
(anonymous) @ index.js:49
onProcessStyle @ index.js:108
onProcessStyle @ PluginsRegistry.js:97
onProcessRule @ PluginsRegistry.js:84
process @ RuleList.js:184
StyleSheet @ StyleSheet.js:93
createStyleSheet @ Jss.js:162
createState @ createHoc.js:315
componentWillUpdate @ createHoc.js:252
updateClassInstance @ react-dom.development.js:13453
updateClassComponent @ react-dom.development.js:15093
beginWork @ react-dom.development.js:15980
performUnitOfWork @ react-dom.development.js:19102
workLoop @ react-dom.development.js:19143
renderRoot @ react-dom.development.js:19228
performWorkOnRoot @ react-dom.development.js:20165
performWork @ react-dom.development.js:20075
performSyncWork @ react-dom.development.js:20049
requestWork @ react-dom.development.js:19904
scheduleWork @ react-dom.development.js:19711
scheduleRootUpdate @ react-dom.development.js:20415
updateContainerAtExpirationTime @ react-dom.development.js:20441
updateContainer @ react-dom.development.js:20509
push../node_modules/react-dom/cjs/react-dom.development.js.ReactRoot.render @ react-dom.development.js:20820
(anonymous) @ react-dom.development.js:20974
unbatchedUpdates @ react-dom.development.js:20292
legacyRenderSubtreeIntoContainer @ react-dom.development.js:20970
render @ react-dom.development.js:21037
./src/index.js @ index.js:6
__webpack_require__ @ bootstrap:782
fn @ bootstrap:150
0 @ serviceWorker.js:135
__webpack_require__ @ bootstrap:782
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ main.chunk.js:1
index.js:1446 Warning: [JSS] Could not find the referenced rule circle2 in Loading, Themed, Dynamic.
function.console.(anonymous function) @ index.js:1446
warning @ browser.js:43
(anonymous) @ index.js:49
onProcessStyle @ index.js:108
onProcessStyle @ PluginsRegistry.js:97
onProcessRule @ PluginsRegistry.js:84
process @ RuleList.js:184
StyleSheet @ StyleSheet.js:93
createStyleSheet @ Jss.js:162
createState @ createHoc.js:315
componentWillUpdate @ createHoc.js:252
updateClassInstance @ react-dom.development.js:13453
updateClassComponent @ react-dom.development.js:15093
beginWork @ react-dom.development.js:15980
performUnitOfWork @ react-dom.development.js:19102
workLoop @ react-dom.development.js:19143
renderRoot @ react-dom.development.js:19228
performWorkOnRoot @ react-dom.development.js:20165
performWork @ react-dom.development.js:20075
performSyncWork @ react-dom.development.js:20049
requestWork @ react-dom.development.js:19904
scheduleWork @ react-dom.development.js:19711
scheduleRootUpdate @ react-dom.development.js:20415
updateContainerAtExpirationTime @ react-dom.development.js:20441
updateContainer @ react-dom.development.js:20509
push../node_modules/react-dom/cjs/react-dom.development.js.ReactRoot.render @ react-dom.development.js:20820
(anonymous) @ react-dom.development.js:20974
unbatchedUpdates @ react-dom.development.js:20292
legacyRenderSubtreeIntoContainer @ react-dom.development.js:20970
render @ react-dom.development.js:21037
./src/index.js @ index.js:6
__webpack_require__ @ bootstrap:782
fn @ bootstrap:150
0 @ serviceWorker.js:135
__webpack_require__ @ bootstrap:782
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ main.chunk.js:1
index.js:1446 Warning: [JSS] Could not find the referenced rule hover in ArwesSounds(Frame), Themed, Dynamic.
function.console.(anonymous function) @ index.js:1446
warning @ browser.js:43
(anonymous) @ index.js:49
onProcessStyle @ index.js:108
onProcessStyle @ PluginsRegistry.js:97
onProcessRule @ PluginsRegistry.js:84
process @ RuleList.js:184
StyleSheet @ StyleSheet.js:93
createStyleSheet @ Jss.js:162
createState @ createHoc.js:315
componentWillUpdate @ createHoc.js:252
updateClassInstance @ react-dom.development.js:13453
updateClassComponent @ react-dom.development.js:15093
beginWork @ react-dom.development.js:15980
performUnitOfWork @ react-dom.development.js:19102
workLoop @ react-dom.development.js:19143
renderRoot @ react-dom.development.js:19228
performWorkOnRoot @ react-dom.development.js:20165
performWork @ react-dom.development.js:20075
performSyncWork @ react-dom.development.js:20049
requestWork @ react-dom.development.js:19904
scheduleWork @ react-dom.development.js:19711
scheduleRootUpdate @ react-dom.development.js:20415
updateContainerAtExpirationTime @ react-dom.development.js:20441
updateContainer @ react-dom.development.js:20509
push../node_modules/react-dom/cjs/react-dom.development.js.ReactRoot.render @ react-dom.development.js:20820
(anonymous) @ react-dom.development.js:20974
unbatchedUpdates @ react-dom.development.js:20292
legacyRenderSubtreeIntoContainer @ react-dom.development.js:20970
render @ react-dom.development.js:21037
./src/index.js @ index.js:6
__webpack_require__ @ bootstrap:782
fn @ bootstrap:150
0 @ serviceWorker.js:135
__webpack_require__ @ bootstrap:782
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ main.chunk.js:1
index.js:1446 Warning: [JSS] Could not find the referenced rule hover in ArwesSounds(Frame), Themed, Dynamic.
function.console.(anonymous function) @ index.js:1446
warning @ browser.js:43
(anonymous) @ index.js:49
onProcessStyle @ index.js:108
onProcessStyle @ PluginsRegistry.js:97
onProcessRule @ PluginsRegistry.js:84
process @ RuleList.js:184
StyleSheet @ StyleSheet.js:93
createStyleSheet @ Jss.js:162
createState @ createHoc.js:315
componentWillUpdate @ createHoc.js:252
updateClassInstance @ react-dom.development.js:13453
updateClassComponent @ react-dom.development.js:15093
beginWork @ react-dom.development.js:15980
performUnitOfWork @ react-dom.development.js:19102
workLoop @ react-dom.development.js:19143
renderRoot @ react-dom.development.js:19228
performWorkOnRoot @ react-dom.development.js:20165
performWork @ react-dom.development.js:20075
performSyncWork @ react-dom.development.js:20049
requestWork @ react-dom.development.js:19904
scheduleWork @ react-dom.development.js:19711
enqueueSetState @ react-dom.development.js:12936
push../node_modules/react/cjs/react.development.js.Component.setState @ react.development.js:356
(anonymous) @ Arwes.js:272
Promise.then (async)
loadResources @ Arwes.js:271
componentDidMount @ Arwes.js:155
commitLifeCycles @ react-dom.development.js:16998
commitAllLifeCycles @ react-dom.development.js:18512
callCallback @ react-dom.development.js:147
invokeGuardedCallbackDev @ react-dom.development.js:196
invokeGuardedCallback @ react-dom.development.js:250
commitRoot @ react-dom.development.js:18717
completeRoot @ react-dom.development.js:20247
performWorkOnRoot @ react-dom.development.js:20170
performWork @ react-dom.development.js:20075
performSyncWork @ react-dom.development.js:20049
requestWork @ react-dom.development.js:19904
scheduleWork @ react-dom.development.js:19711
scheduleRootUpdate @ react-dom.development.js:20415
updateContainerAtExpirationTime @ react-dom.development.js:20441
updateContainer @ react-dom.development.js:20509
push../node_modules/react-dom/cjs/react-dom.development.js.ReactRoot.render @ react-dom.development.js:20820
(anonymous) @ react-dom.development.js:20974
unbatchedUpdates @ react-dom.development.js:20292
legacyRenderSubtreeIntoContainer @ react-dom.development.js:20970
render @ react-dom.development.js:21037
./src/index.js @ index.js:6
__webpack_require__ @ bootstrap:782
fn @ bootstrap:150
0 @ serviceWorker.js:135
__webpack_require__ @ bootstrap:782
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ main.chunk.js:1
index.js:1446 Warning: [JSS] Could not find the referenced rule circle2 in Loading, Themed, Dynamic.
function.console.(anonymous function) @ index.js:1446
warning @ browser.js:43
(anonymous) @ index.js:49
onProcessStyle @ index.js:108
onProcessStyle @ PluginsRegistry.js:97
onProcessRule @ PluginsRegistry.js:84
process @ RuleList.js:184
StyleSheet @ StyleSheet.js:93
createStyleSheet @ Jss.js:162
createState @ createHoc.js:315
componentWillUpdate @ createHoc.js:252
updateClassInstance @ react-dom.development.js:13453
updateClassComponent @ react-dom.development.js:15093
beginWork @ react-dom.development.js:15980
performUnitOfWork @ react-dom.development.js:19102
workLoop @ react-dom.development.js:19143
renderRoot @ react-dom.development.js:19228
performWorkOnRoot @ react-dom.development.js:20165
performWork @ react-dom.development.js:20075
performSyncWork @ react-dom.development.js:20049
requestWork @ react-dom.development.js:19904
scheduleWork @ react-dom.development.js:19711
enqueueSetState @ react-dom.development.js:12936
push../node_modules/react/cjs/react.development.js.Component.setState @ react.development.js:356
(anonymous) @ Arwes.js:272
Promise.then (async)
loadResources @ Arwes.js:271
componentDidMount @ Arwes.js:155
commitLifeCycles @ react-dom.development.js:16998
commitAllLifeCycles @ react-dom.development.js:18512
callCallback @ react-dom.development.js:147
invokeGuardedCallbackDev @ react-dom.development.js:196
invokeGuardedCallback @ react-dom.development.js:250
commitRoot @ react-dom.development.js:18717
completeRoot @ react-dom.development.js:20247
performWorkOnRoot @ react-dom.development.js:20170
performWork @ react-dom.development.js:20075
performSyncWork @ react-dom.development.js:20049
requestWork @ react-dom.development.js:19904
scheduleWork @ react-dom.development.js:19711
scheduleRootUpdate @ react-dom.development.js:20415
updateContainerAtExpirationTime @ react-dom.development.js:20441
updateContainer @ react-dom.development.js:20509
push../node_modules/react-dom/cjs/react-dom.development.js.ReactRoot.render @ react-dom.development.js:20820
(anonymous) @ react-dom.development.js:20974
unbatchedUpdates @ react-dom.development.js:20292
legacyRenderSubtreeIntoContainer @ react-dom.development.js:20970
render @ react-dom.development.js:21037
./src/index.js @ index.js:6
__webpack_require__ @ bootstrap:782
fn @ bootstrap:150
0 @ serviceWorker.js:135
__webpack_require__ @ bootstrap:782
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ main.chunk.js:1
index.js:1446 Warning: [JSS] Could not find the referenced rule hover in ArwesSounds(Frame), Themed, Dynamic.
### Your environment

- Which browser and its version is affected.
- Which node and npm are used.

### Steps to reproduce

Any browser does this....

I just dont want the sounds from the project that is all.
Thanks

**Comment by romelperez** [comment]
Hi @Josep-Jesus-Bigorra-Algaba !

That error comes from the JSS dependency. But functionality should not be affected. The frames will not highlight when the mouse hovers them.

For the next release, that dependency will be updated to fix the problem.

Thanks for using Arwes!

**Comment by InsOpDe** [comment]
Still having the same problem. I get it when adding a `<Button>`
