### ISSUE TITLE
is there any separate css file?

### ISSUE THREAD

**Issue by JadeTao** [arwesjs/arwes#14]
### Subject of the issue

a set of `.css` is better.

is there any plan about it?

**Comment by romelperez** [comment]
Hi @JadeTao !

Nope, the plan for the project is to continue with [A Unified Styling Language](https://medium.com/seek-blog/a-unified-styling-language-d0c208de2660), a CSS in JS implementation.

I wrote my reasons over here: [CSS in JavaScript with JSS and React](https://medium.com/jobsity/css-in-javascript-with-jss-and-react-54cdd2720222).

Thanks for asking!
